### ISSUE TITLE
Dockerhub?

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npmo-docker#39]
Would be nice to have the image on hub.docker.com so that apps like Kitematic can pull in a UI.

**Comment by bcoe** [comment]
@kevinSuttle there have actually been some efforts to do this, I have all the images here:

https://hub.docker.com/u/bcoe/

And I've been working on a docker-compose version of on-site:

https://github.com/npm/npmo-docker-compose

Unfortunately, we don't yet have a story for the admin-console or easy configuration management in the docker-compose version.

**Comment by kevinSuttle** [comment]
Right on. Good to know. Thank @bcoe!
