### ISSUE TITLE
Status of this container

### ISSUE THREAD

**Issue by wesleytodd** [npm/npmo-docker#60]
Hey!  I was wondering the status of this container?

We were hoping to actually run a container for our permanent install of npm on-site, but it doesn't look like this container is really setup to do that?

Thanks for any help you can give!

**Comment by wesleytodd** [comment]
I see that something changed and the new installer package sets up a docker container for us.  Sorry for taking your time :)

**Comment by nexdrew** [comment]
@wesleytodd Hey Wes, no problem!

Just to confirm what you already found, this repo started out as a way to build the npm Enterprise product as a single Docker container. However, we found that using Replicated to help build and distribute the product ended up being a much better solution.

So this repository, which we use to define all the Docker containers that make up the product, still has some unused cruft left behind. Basically anything not under the `replicated` directory is no longer used.

The repository for the installer can be found here: https://github.com/npm/npmo-installer

When installing npm On-Site/Enterprise, you should use the `npmo` installer - it makes things much easier!

```
sudo npm install npmo -g --unsafe
```

Let us know if you have any more questions.

**Comment by wesleytodd** [comment]
Thanks!! We got everything setup with the installer and it seems to be
working.
